version: '3'

services:

  laravel:
    image: edsonluiz/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: edsonluiz/nginx-com-vim
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge